### ISSUE TITLE
How to set webpack.config

### ISSUE THREAD

**Issue by ClarkFrench** [joevbruno/vs-fix-sourcemaps#1]
Looks Very useful.
I cannot get the import statement to work in the webpack config.  import is not recognized as a keyword.  I am new to node so please forgive the newbie type question.
Can you provide an example webpackconfig. with the example code placed in it.

**Comment by Sleepyowl** [comment]
@ClarkFrench `import VSFixSourceMapsPlugin from 'vs-fix-sourcemaps';` is ECMAScript 6 syntax. Long story short, just replace it with `var VSFixSourceMapsPlugin = require('vs-fix-sourcemaps');`
