### ISSUE TITLE
Typescript, UglifyJS, and Versions 0.0.7 - 1.0 of vs-fix-sourcemaps

### ISSUE THREAD

**Issue by nippur72** [joevbruno/vs-fix-sourcemaps#3]
Just to report that I'm able to debug in VS2015 and webpack **without** this plugin.

This is what I have in `webpack.config.js`:

``` js
module.exports = {
    module: {
        preLoaders: [
            {
                test: /\.js$/,
                loader: "source-map-loader"
            }
        ]
    },
    entry: {
        app: "./src/app.js",
        vendor: [ "./bundle/bundle-maker.js" ]
    },
    cache: true,
    debug: true,
    devtool: "source-map",
    plugins: plugins,
    output: {
        libraryTarget: "this",
        path: "./bundle",
        filename: "app.js",
        sourceMapFilename: "[name].js.map",
        devtoolModuleFilenameTemplate: "[resource-path]"
    }
}
```

anyway there's one thing that I'm missing: while the debugger is stopped on a breakpoint, hovering the mouse over a variable name doesn't result in the tooltip with the variable value to show up. I don't know why... does this work with the plugin?

**Comment by joevbruno** [comment]
@nippur72 Yes, it does... sometimes. There are a couple of contributing issue, which effect Visual Studio Debugging of JSX / Transpiled ES6/7/8 files. 
1. Some of them seem to be related to the way webpack inserts comments, because if I utilize the Uglify plugin to strip comments, things get much closer to working without any additional plugins. 
2. Part of the problem seems to be related to Javascript [sourcemaps](https://bugs.chromium.org/p/chromium/issues/detail?id=327092).
3. Lastly, another contributing factor seems to be related to certain babel plugins. For instance, with React, I can use the react-hot-loader plugin to hot reload with Visual Studio, but the React-Transform babel plugins break things. 

This project has unfortunately been sidelined for the past month while I had to work on other things, but over the next month I will have to pick it back up as I need to solve the problem, if possible, before May.

**Comment by cellvia** [comment]
i cant get EITHER of these to work, using VS2015... wondering what im doing wrong!

im using the webpack-dev-server  have you guys been able to get this to work w/ that?

**Comment by joevbruno** [comment]
I haven't actually tried it with the webpack-dev-server. Currently, we have a couple of variations though, including an express server (with the webpack dev/hot middleware) and browsersync with that same middleware. To be honest, if you CAN use a text-editor like Atom with the React and Babel plugins available to it, the developer experience is so much better (or even Visual Studio Code, but I personally don't like setup and dependencies on typescript). You can get pretty darn good autocomplete, syntax highlighting of the latest ES7/8 features, and more, and you can set breakpoints in Chrome. This is my general and preferred workflow; however, for work (and for various reasons), we have a 'dependency' upon VS 2015. If you are not in that boat, and VS2015 is a matter of preference, then I would encourage you to give Atom, Sublime of VS Code a fair shake. They are much better at modern front-end development. As I said, I use Atom with a handful of plugins and the experience is smooth. If, however, you are in a similar boat, something to try is: 
- VS Breakpoints only work from IE. So make sure you are running your project in debug mode with IE as the selected browser. You should see all of your dependencies fill up in the solutions explorer when you hit a page with your react code.
- If that isn't happening, something else is going on, which could be related to your .babelrc file. If you have any of the transform plugins, this tends to screw things up in VS2015. Perhaps try removing them.
- to add the webpack uglify plugin and see if VS can hit breakpoints on SOME lines. It won't work every time, but that at least lets you know it is something again with webpack's comments.

If you do these and you still are no closer, post your webpack config and .babelrc files and I will take a look.

**Comment by cellvia** [comment]
thank you.  yeah i personally hate VS, but debugging w/ VS is a requirement for us switching fully to webpack.  i'll try it w/ IE, cause i was using it with chrome when it wasnt working... thank you!

**Comment by joevbruno** [comment]
@cellvia did you have any luck? Did you see my comment [here](https://github.com/webpack/webpack/issues/1502)

**Comment by joevbruno** [comment]
@nippur72 could you provide some additional information.

webpack version
babel version (if applicable)

I don't see any sort of transforms or loaders in your webpack configuration. Are you using Babel?
If so, can you post your .babelrc file?

**Comment by nippur72** [comment]
@joevbruno 
webpack is 1.13.0
VS is VS2015 Community Edition V 14.0.25123.00 Update 2
tsc is 1.8.9
App is an ASP.NET web site (.cshtml), launched in Explorer 11 from Visual Studio.
No babel is involved.

Recently I switched using `ts-loader` in webpack, but it worked even without that (by loading compiled .js).

Below is my `webpack.config.js`:

``` ts
var development = require("./src/debug").developmentMode;

console.log("\n\n***************************")
if(!development) console.log("building for PRODUCTION");
else             console.log("building for DEVELOPMENT");
console.log("***************************\n\n")

var webpack = require('webpack');

// plugins
var uglify = new webpack.optimize.UglifyJsPlugin({ compress: { warnings: false } });
var reactProd = new webpack.DefinePlugin({'process.env': {'NODE_ENV': development ? '"development"' : '"production"'}});
var commonChunks = new webpack.optimize.CommonsChunkPlugin("vendor", "vendor.bundle.js");
var plugins = [ reactProd, commonChunks ];
if(!development) plugins.push(uglify);

module.exports = {
    module: {

        loaders: [
            { test: /\.tsx?$/, loader: "ts-loader" }
        ],

        preLoaders: [
            { test: /\.js$/, loader: "source-map-loader" }
        ]
    },
    entry: {
        app: "./src/app.js",
        vendor: [
            "./bundle/bundle-maker.js",
            "tslib",
            "deep-diff"
        ]
    },
    cache: true,
    debug: true,
    devtool: "source-map",

    resolve: {
        // Add '.ts' and '.tsx' as resolvable extensions.
        extensions: ["", ".webpack.js", ".web.js", ".ts", ".tsx", ".js"]
    },

    plugins: plugins,
    output: {
        libraryTarget: "this",
        path: "./bundle",
        filename: "app.js",
        sourceMapFilename: "[name].js.map",
        devtoolModuleFilenameTemplate: "[resource-path]"
    }
}
```

**Comment by joevbruno** [comment]
Thanks @nippur72. Thank it really helpful. I built the plugin to try to solve debugging issue that arose as a result of babel transpilation. The plugin worked with Babel 5, but does not seem to with Babel 6 unless the code is uglified, which introduces `names` into the sourcemap, which Visual Studio uses as `symbols` to map for debugging.

**Comment by IAMtheIAM** [comment]
For some reason I'm seeing multiple duplicates of each file. Does anyone have an idea why this is happening? 

I got it to work without using this plugin too, but I had to include the Uglify plugin, otherwise the source maps didn't work right.

![repeat_files](https://cloud.githubusercontent.com/assets/13709948/15408388/d68269c8-1dc4-11e6-9f43-65643582241b.png)

The same duplicates happened with and without this plugin.

**Comment by joevbruno** [comment]
@IAMtheIAM  check out my comment [here](https://github.com/webpack/webpack/issues/1502).

This duplication happens because the names mappings are still not completely correct. Are you using babel? If so, what version?

**Comment by IAMtheIAM** [comment]
I'm actually not using babel currently. I'm using the [Angular 2 webpack starter repo](https://github.com/AngularClass/angular2-webpack-starter) webpack config.

**Comment by nippur72** [comment]
@IAMtheIAM I too get duplicates if I turn on `uglifyjs`.

**Comment by joevbruno** [comment]
@IAMtheIAM what does your uglify config look like?

**Comment by joevbruno** [comment]
@cellvia @nippur72 @IAMtheIAM new version of the plugin. You should give it a try!

**Comment by nippur72** [comment]
Ah! this is just ridiculous:

I was using TypeScript + webpack but NOT this plugin as per my original post, and all was fine. 

Then, after some refactoring (moving files etc) all of sudden Visual Studio stopped loading sourcemaps! I tried everything to get them back to no avail... spent lot of time, then I remembered of this plugin and gave it a try. 

Well now my sourcemaps are back thanks to this plugin!

So I can confirm it works with TypeScript.

> It may work with Typescript, but it has not been tested, and I do not plan on supporting Typescript - though I will happily accept your PR.

**Comment by joevbruno** [comment]
@nippur72 Thanks for confirming things are working. Here are a few things I found that break Visual Studio debugging ( I am guessing in your refactoring, you used one of them):

Note: this plugin fixes all of these (and more). All examples below refer to ES6+ syntax
- `export default` and `export` in the same file.
- exporting a function - you have to assign the function a `const` and `export const`
- CSS modules import statements in a `index` file.
- creating a `class` that only has a constructor.
- static class properties

Perhaps, you used one of these?

If you notice anything else breaking Visual Studio, please let me know! **Also, are you still using the uglify plugin strictly for debugging? By using this plugin's 1.0+ version, you should not need uglify, which means you will no longer get duplicates in the solution explorer** =)  Can you verify debugging works for you without the uglify plugin?
<img width="393" alt="screen shot 2016-06-01 at 11 37 49 am" src="https://cloud.githubusercontent.com/assets/4028963/15895746/f171585c-2d5a-11e6-9a20-7cebbca6c2d4.png">
<img width="373" alt="screen shot 2016-06-01 at 11 38 17 am" src="https://cloud.githubusercontent.com/assets/4028963/15895747/f1739112-2d5a-11e6-8db0-b1e557d7ad12.png">

**Comment by nippur72** [comment]
> Perhaps, you used one of these?

none of them. My suspects go to having a mix of `import` and `require` in the same file, but I am not sure. What I actually did was moving files from one bundle to another, with the result that some files appeared, most other not, without any apparent reason. The simple adoption of the plugin fixed it.

> Can you verify debugging works for you without the uglify plugin?

yes, it works without the uglify plugin (which I usually turn off when in development mode).

I should also mention that the next TS 2.0 version will fix a related issue (see https://github.com/Microsoft/TypeScript/issues/8011) so I'll have to recheck this when then new release is out.

**Comment by joevbruno** [comment]
@nippur72 Thanks for the feedback. If you figure out what exactly is breaking your build, I would love to know. I am trying to find all of problematic variations.

**Comment by cellvia** [comment]
thanks @joevbruno  i will give it a try soon and report back soon ! 👍

**Comment by cellvia** [comment]
just wanted to let you know, this version works a lot better :-)  havent tested it with dev server yet, but it works for static builds, and thats mainly what i needed for the folks who arent ready to move on from VS :-)  thank you!

**Comment by joevbruno** [comment]
@cellvia 👍
